Parameters:    
    LatestAmiId:
        # Type: "AWS::SSM::Parameter::Value<String>"
        # Default: "/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2"
        Type:  "String"
        Default: "ami-04d29b6f966df1537"
    InstanceType:
        Type: "String"
        Default: "t3.small"

Resources:
    EC2Instance:
        Type: AWS::EC2::Instance
        Metadata: 
            AWS::CloudFormation::Init:
                config:
                    packages:
                        yum:
                            docker: []
                            git: []
                            jq: []
                            # httpd:  []  # TODO Temporary
                    services:
                        sysvinit:
                            docker:
                                enabled: "true"
                                ensureRunning: "true"
#                            httpd:
#                                enabled: "true"
#                                ensureRunning: "true"

                    commands:
                        a1_install_docker: 
                            command:
                                'Fn::Join':
                                    - "\n"
                                    - - sudo service docker start
                                      - sudo usermod -a -G docker ec2-user
                                      - sudo curl -L https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
                                      - sudo chmod +x /usr/local/bin/docker-compose
                                      - git clone https://github.com/JohnLockwood/brownbag.git
                                      - cd brownbag
                                      - mkdir secret
                                      - aws ssm get-parameter --with-decrypt --name /languagelearn/production/environment --region us-east-1 | jq -r .Parameter.Value > secret/.env
                                      - docker-compose build
                                      - docker-compose up&
        Properties:
            ImageId: !Ref LatestAmiId
            InstanceType: !Ref InstanceType
            IamInstanceProfile: "EC2SSMReadOnly"
            SecurityGroups:
            - !Ref WebSecurityGroup
            - !Ref SSHSecurityGroup
            BlockDeviceMappings:
            -
                DeviceName: /dev/sda1
                Ebs:
                    VolumeSize: 50
            UserData: !Base64 
                'Fn::Join':
                    - ''
                    - - |
                        #!/bin/bash -xe
                      - |
                        # Install the files and packages from the metadata
                      - '/opt/aws/bin/cfn-init -v '
                      - '         --stack '
                      - !Ref 'AWS::StackName'
                      - '         --resource EC2Instance '
                      - '         --region '
                      - !Ref 'AWS::Region'
                      - |+

    SSHSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Enable SSH access via port 22
            SecurityGroupIngress:
                CidrIp: 0.0.0.0/0
                FromPort: 22
                IpProtocol: tcp
                ToPort: 22
    WebSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Enable HTTP access via user defined port
            SecurityGroupIngress:
                CidrIp: 0.0.0.0/0
                FromPort: 80
                IpProtocol: tcp
                ToPort: 80

    DNSRecords:
        Type:  AWS::Route53::RecordSet
        Properties:
            Name: "languagelearn.pro"
            HostedZoneId: "Z02334682U89LH3CFGMR8" # LanguageLearn.pro
            Type: A
            ResourceRecords:
                - !GetAtt EC2Instance.PublicIp
            TTL: '300'