Parameters:    
    LatestAmiId:
        # Type: "AWS::SSM::Parameter::Value<String>"
        # Default: "/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2"
        Type:  "String"
        Default: "ami-04d29b6f966df1537"
    InstanceType:
        Type: "String"
        Default: "t3.small"

Resources:
    EC2Instance:
        Type: AWS::EC2::Instance
        Metadata: 
            AWS::CloudFormation::Init:
                config:
                    packages:
                        yum:
                            docker: []
                            git: []
                            httpd:  []  # TODO Temporary
                    services:
                        sysvinit:
                            docker:
                                enabled: "true"
                                ensureRunning: "true"
                    commands:
                        a1_install_docker: 
                            command:
                                'Fn::Join':
                                    - "\n"
                                    - - echo skipping sudo service docker start
                                      - sudo usermod -a -G docker ec2-user
                                      - sudo curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
                                      - sudo chmod +x /usr/local/bin/docker-compose
        Properties:
            ImageId: !Ref LatestAmiId
            InstanceType: !Ref InstanceType
            IamInstanceProfile: "EC2SSMReadOnly"
            AvailabilityZone: "us-east-1b"
            SecurityGroups:
            - !Ref WebSecurityGroup
            - !Ref SSHSecurityGroup
            Volumes:
                - Device: /dev/sda1
                  VolumeId: !Ref BrownbagEC2Volume
            UserData: !Base64 
                'Fn::Join':
                    - ''
                    - - |
                        #!/bin/bash -xe
                      - |
                        # Install the files and packages from the metadata
                      - '/opt/aws/bin/cfn-init -v '
                      - '         --stack '
                      - !Ref 'AWS::StackName'
                      - '         --resource EC2Instance '
                      - '         --region '
                      - !Ref 'AWS::Region'
                      - |+


    BrownbagEC2Volume:
        Type:  AWS::EC2::Volume
        DeletionPolicy: Retain
        Properties:
            Encrypted: true
            AvailabilityZone: "us-east-1b"
            Size: 40
            VolumeType:  "gp3"
            Tags:
                - Key: Name
                  Value:  BrownbagEC2Volume
    SSHSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Enable SSH access via port 22
            SecurityGroupIngress:
                CidrIp: 0.0.0.0/0
                FromPort: 22
                IpProtocol: tcp
                ToPort: 22
    WebSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Enable HTTP access via user defined port
            SecurityGroupIngress:
                CidrIp: 0.0.0.0/0
                FromPort: 80
                IpProtocol: tcp
                ToPort: 80

    DNSRecords:
        Type:  AWS::Route53::RecordSet
        Properties:
            Name: "languagelearn.pro"
            HostedZoneId: "Z02334682U89LH3CFGMR8" # LanguageLearn.pro
            Type: A
            ResourceRecords:
                - !GetAtt EC2Instance.PublicIp
            TTL: '300'