version: "3"
services:
  api:
    build: 
      context: .
    ports:
      - "80:80"
    environment:
      RUN_ENVIRONMENT: "development"
  postgres:
    image: "postgres:13.0-alpine"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: api_user
      # POSTGRES_DB: api_development_db
    ports:
    - "5432:5432" 
    volumes:
    - data:/var/lib/postgresql/data 

volumes:
  data:




