version: "3"
services:
  api:
    build: 
      context: api
    ports:
      - 8888:80
    env_file:
      - ./secret/.env.dev
  ui:
      build:
        context: ui
      ports:
        - 8080:80
  postgres:
    image: "postgres:11.8-alpine"
    env_file:
      - ./secret/.env.dev
    ports:
      - "5432:5432"
    volumes:
    - brownbag_data:/var/lib/postgresql/data

volumes:
  brownbag_data:




