version: "3"
services:
  api:
    build: 
      context: .
    ports:
      - "80:80"
    env_file:
      - ./secret/.env.dev
  postgres:
    image: "postgres:13.0-alpine"
    env_file:
      - ./secret/.env.dev
    ports:
      - "5432:5432"
    volumes:
    - data:/var/lib/postgresql/data 

volumes:
  data:




