version: "3"
services:
  api:
    build: 
      context: .
    ports:
      - "80:80"
    env_file:
      - ./secret/.env.dev
  postgres:
    image: "postgres:11.8-alpine"
    env_file:
      - ./secret/.env.dev
    ports:
      - "5432:5432"
    volumes:
    - brownbag_data:/var/lib/postgresql/data

volumes:
  brownbag_data:




