version: '3'
services:
  api:
    build: 
        context: ..
        args:
            -f apicd/Dockerfile
            -t api:latest
    networks:     
      - backend
    networks:
      - frontend
  postgres:
    image: "redis:latest"
    networks:
      - backend

networks:
  frontend:
  backend:
   internal: true
